version: '3'

services:

  database:
    image: postgres
    container_name: database
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres

  api:
    build: ./api
    container_name: api
    links:
      - database
    depends_on:
      - database
    ports:
      - 8080:8080
    volumes:
      - "./api/:/api"
    environment:
      - POKEME_DATABASE_URL=${POKEME_DATABASE_URL}
      - POKEME_DEBUG=${POKEME_DEBUG}
    command: apistar run --port 8080 --host 0.0.0.0
    tty: true
    stdin_open: true

volumes:
  postgres:
    driver: 'local'