version: '3'

services:

  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /var/lib/postgres
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres

  api:
    build: ./api
    restart: on-failure
    container_name: api
    links:
      - db
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - "./api/:/api"
    environment:
      - "${POKEME_DATABASE_URL}:${POKEME_DATABASE_URL}"
    command: apistar run
    tty: true
    stdin_open: true
  